
-- Criar tabela de usuários
CREATE TABLE USERS (
    ID VARCHAR2(36) PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    PERFIL VARCHAR2(20) DEFAULT 'ADM' NOT NULL
);

-- Criar tabela de logs de sincronização
CREATE TABLE SYNC_LOGS (
    ID VARCHAR2(36) PRIMARY KEY,
    EMPRESA_ID VARCHAR2(36) NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(50) NOT NULL,
    DURACAO VARCHAR2(50),
    DETALHES CLOB,
    ERRO CLOB,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Criar tabela de configurações
CREATE TABLE CONFIGURACOES (
    ID VARCHAR2(36) PRIMARY KEY,
    CHAVE VARCHAR2(255) NOT NULL UNIQUE,
    VALOR CLOB NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Índices
CREATE INDEX IDX_SYNC_LOGS_EMPRESA ON SYNC_LOGS(EMPRESA_ID);
CREATE INDEX IDX_SYNC_LOGS_STATUS ON SYNC_LOGS(STATUS);
CREATE INDEX IDX_SYNC_LOGS_TIPO ON SYNC_LOGS(TIPO);

-- Comentários
COMMENT ON TABLE USERS IS 'Tabela de usuários do sistema';
COMMENT ON TABLE SYNC_LOGS IS 'Log de sincronizações entre Sankhya e Oracle';
COMMENT ON TABLE CONFIGURACOES IS 'Configurações globais do sistema';
