
-- Script para criação das tabelas AS_* (espelhamento Sankhya)
-- Conectar usando: SYSTEM/Castro135! em crescimentoerp.nuvemdatacom.com.br:9568/FREEPDB1

-- 1. AS_Parceiro
CREATE TABLE AS_PARCEIRO (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    CODPARC NUMBER(9, 0) NOT NULL,
    NOMEPARC VARCHAR2(150) NOT NULL,
    CGC_CPF VARCHAR2(15),
    CODCID NUMBER(5, 0),
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    TIPPESSOA CHAR(1) CHECK (TIPPESSOA IN ('F', 'J')),
    RAZAOSOCIAL VARCHAR2(150),
    IDENTINSCESTAD VARCHAR2(20),
    CEP VARCHAR2(8),
    CODEND VARCHAR2(100),
    NUMEND VARCHAR2(10),
    COMPLEMENTO VARCHAR2(100),
    CODBAI NUMBER(5, 0),
    LATITUDE VARCHAR2(20),
    LONGITUDE VARCHAR2(20),
    CLIENTE CHAR(1) DEFAULT 'N' CHECK (CLIENTE IN ('S', 'N')),
    CODVEND NUMBER(5, 0),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, CODPARC)
);

-- 2. AS_Produto
CREATE TABLE AS_PRODUTO (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    CODPROD NUMBER(9, 0) NOT NULL,
    DESCRPROD VARCHAR2(250) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    LOCAL VARCHAR2(50),
    MARCA VARCHAR2(50),
    CARACTERISTICAS VARCHAR2(4000),
    UNIDADE VARCHAR2(6),
    VLRCOMERC NUMBER(15, 2),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, CODPROD)
);

-- 3. AS_Estoque
CREATE TABLE AS_ESTOQUE (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    CODPROD NUMBER(9, 0) NOT NULL,
    CODLOCAL NUMBER(5, 0) NOT NULL,
    ESTOQUE NUMBER(15, 4) DEFAULT 0,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    CONTROLE CHAR(1),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, CODPROD, CODLOCAL)
);

-- 4. AS_TipoNegociacao
CREATE TABLE AS_TIPONEGOCIACAO (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    CODTIPVENDA NUMBER(5, 0) NOT NULL,
    DESCRTIPVENDA VARCHAR2(100) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, CODTIPVENDA)
);

-- 5. AS_TipoOperacao
CREATE TABLE AS_TIPOOPERACAO (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    CODTIPOPER NUMBER(5, 0) NOT NULL,
    DESCROPER VARCHAR2(100) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, CODTIPOPER)
);

-- 6. AS_Vendedor
CREATE TABLE AS_VENDEDOR (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    CODVEND NUMBER(5, 0) NOT NULL,
    APELIDO VARCHAR2(50) NOT NULL,
    TIPVEND CHAR(1) CHECK (TIPVEND IN ('V', 'G')),
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    CODGER NUMBER(5, 0),
    EMAIL VARCHAR2(100),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, CODVEND)
);

-- 7. AS_Financeiro
CREATE TABLE AS_FINANCEIRO (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    NUFIN NUMBER(15, 0) NOT NULL,
    CODPARC NUMBER(9, 0) NOT NULL,
    CODEMP NUMBER(5, 0) NOT NULL,
    VLRDESDOB NUMBER(15, 2) DEFAULT 0,
    DTVENC DATE,
    DTNEG DATE,
    PROVISAO CHAR(1) CHECK (PROVISAO IN ('S', 'N')),
    DHBAIXA TIMESTAMP,
    VLRBAIXA NUMBER(15, 2) DEFAULT 0,
    RECDESP NUMBER(1) DEFAULT 1,
    NOSSONUM VARCHAR2(20),
    CODCTABCOINT NUMBER(5, 0),
    HISTORICO VARCHAR2(250),
    NUMNOTA VARCHAR2(20),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, NUFIN)
);

-- 8. AS_CabecalhoNota
CREATE TABLE AS_CABECALHONOTA (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    NUNOTA NUMBER(15, 0) NOT NULL,
    CODTIPOPER NUMBER(5, 0),
    CODTIPVENDA NUMBER(5, 0),
    TIPMOV CHAR(1),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, NUNOTA)
);

-- 9. AS_ComplementoParc
CREATE TABLE AS_COMPLEMENTOPARC (
    ID_SISTEMA VARCHAR2(50) NOT NULL,
    CODPARC NUMBER(9, 0) NOT NULL,
    SUGTIPNEGSAID NUMBER(5, 0),
    DT_ULT_CARGA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_SISTEMA, CODPARC)
);

-- Criar índices para otimização
CREATE INDEX IDX_AS_PARCEIRO_SISTEMA ON AS_PARCEIRO(ID_SISTEMA);
CREATE INDEX IDX_AS_PRODUTO_SISTEMA ON AS_PRODUTO(ID_SISTEMA);
CREATE INDEX IDX_AS_ESTOQUE_SISTEMA ON AS_ESTOQUE(ID_SISTEMA);
CREATE INDEX IDX_AS_TIPONEG_SISTEMA ON AS_TIPONEGOCIACAO(ID_SISTEMA);
CREATE INDEX IDX_AS_TIPOOP_SISTEMA ON AS_TIPOOPERACAO(ID_SISTEMA);
CREATE INDEX IDX_AS_VENDEDOR_SISTEMA ON AS_VENDEDOR(ID_SISTEMA);
CREATE INDEX IDX_AS_FINANCEIRO_SISTEMA ON AS_FINANCEIRO(ID_SISTEMA);
CREATE INDEX IDX_AS_CABNOTA_SISTEMA ON AS_CABECALHONOTA(ID_SISTEMA);
CREATE INDEX IDX_AS_COMPLPARC_SISTEMA ON AS_COMPLEMENTOPARC(ID_SISTEMA);

-- Comentários
COMMENT ON TABLE AS_PARCEIRO IS 'Espelhamento da tabela TGFPAR do Sankhya';
COMMENT ON TABLE AS_PRODUTO IS 'Espelhamento da tabela TGFPRO do Sankhya';
COMMENT ON TABLE AS_ESTOQUE IS 'Espelhamento da tabela TGEEST do Sankhya';
COMMENT ON TABLE AS_TIPONEGOCIACAO IS 'Espelhamento da tabela TGFTIPVENDA do Sankhya';
COMMENT ON TABLE AS_TIPOOPERACAO IS 'Espelhamento da tabela TGFTOP do Sankhya';
COMMENT ON TABLE AS_VENDEDOR IS 'Espelhamento da tabela TGFVEN do Sankhya';
COMMENT ON TABLE AS_FINANCEIRO IS 'Espelhamento da tabela TGFFIN do Sankhya';
COMMENT ON TABLE AS_CABECALHONOTA IS 'Espelhamento da tabela TGFCAB do Sankhya';
COMMENT ON TABLE AS_COMPLEMENTOPARC IS 'Espelhamento do complemento de parceiros do Sankhya';
